import React from 'react';
import Head from "next/head";
import type { NextPage } from "next";

const Header: NextPage = () => (
  <Head>
    <title>Fuji finance</title>
    <meta
      name="description"
      content="Generated by @rainbow-me/create-rainbowkit"
    />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);

export default Header;
